---
- name: Upgrade system
  package: upgrade=dist update_cache=yes

- name: Install nginx
  package: name=nginx state=latest

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install system nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install nginx site for http requests
  template:
    src: nginx-http.j2
    dest: /etc/nginx/sites-enabled/http

- name: Install nginx site for https site
  template:
    src: nginx-https.j2
    dest: /etc/nginx/sites-enabled/https

- name: Reload nginx to activate specified site
  service: name=nginx state=restarted
