---

- set_fact:
    vstools:
      - xclip
      - xfce4
      - xfce4-goodies
      # VSCOODE live share reqs
      - libssl1.0.0
      - libkrb5-3
      - zlib1g
      - libicu60
      - gnome-keyring
      - libsecret-1-0
      - desktop-file-utils
      - x11-utils

- name: Install vscodetools
  package: name="{{ item }}" state=present
  with_items:
    - "{{ vnctools|default([]) }}"

- name: set gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: yes

- name: install vscode
  apt:
    name: code
    update_cache: true
  when:
    - vscode_install

- name: install vscode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ extensions }}"
  become: true
  become_user: "{{ user }}"

- name: write settings for vscode
  template:
    src: settings.json.j2
    dest: "/home/{{ user }}/.config/Code/User/settings.json"
