---
- block:
  - name: Check the system
    raw: uname -a
    register: OS
    tags:
      - update-users

  - include_tasks: ubuntu.yml
    when: '"Ubuntu" in OS.stdout or "Linux" in OS.stdout'
    tags:
      - update-users

  - name: Sysctl tuning
    sysctl: name="{{ item.item }}" value="{{ item.value }}"
    when: item.item != ""
    with_items:
      - "{{ sysctl|default([]) }}"
    tags:
      - always

  - name: Create a login user
    user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
      groups: # Empty by default, here we give it some groups
      - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      createhome: yes        # Defaults to yes

  - name: Creates shh directory
    file:
      path: "/home/{{ user }}/.ssh"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Authorized Keys
    template:
      src: authorized_keys.j2
      dest: "/home/{{ user }}/.ssh/authorized_keys"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Configs
    template:
      src: editorconfig.j2
      dest: "/home/{{ user }}/.editorconfig"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - meta: flush_handlers

  - meta: flush_handlers
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
